---
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---
```{r}
library(plyr)
library(tidyverse)
library(lme4)
library(lmerTest)
library(rmcorr)
library(ggplot2)
library(viridis)
library(hrbrthemes)
```

```{r}
raw_data <- readr::read_csv("data/data_processed.csv", show_col_types = FALSE)
data <- raw_data



factor_cols <- c("dyad_id", "person_id", "order_id", "treatment", "treatment_name")
data[,factor_cols] <- lapply(data[,factor_cols], factor)
```

```{r}
# Sandbox cell, used for running arbitrary, temporary code (and learning R)
MModel <- lmer(self_presence_score ~ treatment + (1|dyad_id/person_id), REML = TRUE, data = data)
summary(MModel)
# anova(MModel)
```

```{r}
# Plotting code
# ggplot(data, aes(x = "A")) +
  # geom_histogram() +
  # facet_wrap(~ social_presence_score)

plot_data <- data %>% pivot_longer(cols = ends_with("score"), names_pattern = "(\\w+)_score", names_to = c("score"))
plot_data <- plot_data[plot_data$score %in% c("physical_presence", "social_presence", "self_presence"),]

plot_data$score <- mapvalues(plot_data$score, 
          from=c("physical_presence","social_presence","self_presence"), 
          to=c("physical","social","self"))

data %>% 
  # transform(score = factor(score, levels=c("physical", "social", "self"))) %>%
  
  ggplot( aes(x = treatment, y = social_presence_score)) +
  geom_point() +
  facet_wrap(~person_id)
  # scale_fill_viridis(discrete = TRUE, alpha=0.6) +
  # theme_ipsum() +
  # theme(
  #   legend.position="none",
  #   plot.title = element_text(size=11)
  # ) +
  # ggtitle("A boxplot with jitter") +
  # xlab("condition")
```

```{r}
# Plotting code
# ggplot(data, aes(x = "A")) +
  # geom_histogram() +
  # facet_wrap(~ social_presence_score)

plot_data <- data %>% pivot_longer(cols = ends_with("score"), names_pattern = "(\\w+)_score", names_to = c("score"))
plot_data <- plot_data[plot_data$score %in% c("physical_presence", "social_presence", "self_presence"),]

plot_data$score <- mapvalues(plot_data$score, 
          from=c("physical_presence","social_presence","self_presence"), 
          to=c("Physical pres.","Social pres.","Self-pres."))

plot_data$treatment <- mapvalues(plot_data$treatment, 
          from=c("A","B","C"), 
          to=c("Static","Eye","Full"))

plot_data %>% 
  transform(score = factor(score, levels=c("Physical pres.","Social pres.","Self-pres."))) %>%
  
  ggplot( aes(x = treatment, y = value, fill = treatment)) +
  geom_boxplot(outlier.shape = NA, colour = "#444444") +
  scale_fill_viridis(discrete = TRUE, alpha=0.4) +
  geom_jitter(color="black", width=.3, size=.8, alpha=1) +
  facet_wrap(~score) + 
  theme_ipsum() +
  scale_y_continuous(breaks = seq(1, 7, by = 1)) + 
  theme(
    legend.position="none",
    plot.title = element_text(size=11),
    rect = element_rect(fill = "transparent"),
    # axis.ticks.y.left = element_line(color="black"),
    # axis.minor.ticks.y.left = element_line(color="black")
  ) +
  # ggtitle("A boxplot with jitter") +
  xlab("condition") +
  ylab("score")
ggsave(file="presence-box_plot.svg", width=6, height=4)
```